update workflow for Moodle 5.1+ paths

diff --git a/.github/workflows/moodle-ci.yml b/.github/workflows/moodle-ci.yml
--- a/.github/workflows/moodle-ci.yml
+++ b/.github/workflows/moodle-ci.yml
@@ -111,16 +111,47 @@ jobs:
 
       - name: PHPUnit tests
         if: ${{ always() }}
-        run: |
-          # In PHP Unit 11 the coverage information is inside a source tag instead of coverage.
-          # To use the same xml file for Moodle 4.5 and Moodle 5.0+ the tag is changed directly here.
-          
+        run: |  
           if [[ "${{ matrix.moodle-branch }}" == "MOODLE_500_STABLE" || "${{ matrix.moodle-branch }}" == "MOODLE_501_STABLE" ]]; then
             echo "Moodle 5.x detected: Patching phpunit.xml for PHPUnit 11 compatibility..."
             sed -i 's/<coverage>/<source>/g' moodle/local/oer/phpunit.xml
             sed -i 's/<\/coverage>/<\/source>/g' moodle/local/oer/phpunit.xml
           fi
           
+          moodle-plugin-ci phpunit --coverage-text --fail-on-warning
+
+      - name: PHPUnit tests
+        if: ${{ always() }}
+        run: |
+          
+          # In PHP Unit 11 the coverage information is inside a source tag instead of coverage.
+          # To use the same xml file for Moodle 4.5 and Moodle 5.0+ the tag is changed directly here.
+          # Since Moodle 5.1 the code is inside a public folder the folder will be read dynamically to 
+          # find the phpunit.xml
+          
+          if [ -d "moodle/public/local/oer" ]; then
+            PLUGIN_PATH="moodle/public/local/oer"
+            echo "Path detected: Moodle 5.1+ structure ($PLUGIN_PATH)"
+          else
+            PLUGIN_PATH="moodle/local/oer"
+            echo "Path detected: Legacy structure ($PLUGIN_PATH)"
+          fi
+
+          CONFIG_FILE="$PLUGIN_PATH/phpunit.xml"
+          
+          # Check if file exists before proceeding
+          if [ ! -f "$CONFIG_FILE" ]; then
+             echo "::error::Config file not found at $CONFIG_FILE"
+             ls -la $PLUGIN_PATH
+             exit 1
+          fi
+
+          if [[ "${{ matrix.moodle-branch }}" == "MOODLE_500_STABLE" || "${{ matrix.moodle-branch }}" == "MOODLE_501_STABLE" || "${{ matrix.moodle-branch }}" == "master" ]]; then
+            echo "Applying PHPUnit 11 patch (<coverage> -> <source>)..."
+            sed -i 's/<coverage>/<source>/g' "$CONFIG_FILE"
+            sed -i 's/<\/coverage>/<\/source>/g' "$CONFIG_FILE"
+          fi
+
           moodle-plugin-ci phpunit --coverage-text --fail-on-warning
 
       - name: Behat features
